In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv('Advertising.csv')
df.head()

,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [4]:
X= df.drop('sales',axis=1)
y=df['sales']

### Polynomial Conversion

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
p_converter= PolynomialFeatures(degree=3,include_bias=False)

In [9]:
p_features= p_converter.fit_transform(X)

In [10]:
p_features.shape

(200, 19)

### Train Test Split

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test= train_test_split(p_features, y, test_size=0.25, random_state=101)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc= StandardScaler()

In [15]:
sc.fit(X_train)

StandardScaler()

In [16]:
sc_X_train= sc.transform(X_train) #scalled x train
sc_X_test= sc.transform(X_test)

### Ridge Regression

In [18]:
from sklearn.linear_model import Ridge

In [19]:
r_model= Ridge(alpha=10)

In [21]:
r_model.fit(sc_X_train,y_train)

Ridge(alpha=10)

In [24]:
r_model.predict(sc_X_test)

array([13.76978596, 19.17258573, 11.8395987 , 16.28249355,  8.79024264,
        7.91550006, 20.13465522, 16.93596643, 10.19361009, 19.79784545,
       10.27212211, 13.37963624, 12.19587158, 23.24722392, 19.15824725,
        9.66081559, 12.8148234 ,  9.00844275,  8.70249034, 21.4831851 ,
        8.11925208, 18.83138339, 28.371303  , 25.05626303,  8.96344868,
       11.78569785, 20.85201761,  9.26879405, 12.20042045,  9.06295713,
        9.23528171, 19.88844988, 10.46378952,  7.80069981, 17.68756241,
        9.23947418, 10.07857799,  9.35123087,  8.58627798, 10.67356127,
       11.69203166, 10.32915612, 10.86822536,  8.34388224, 11.29431307,
       10.26343115,  7.87511278, 15.28949745, 12.97710494, 22.51457763])

In [25]:
r_test_pred= r_model.predict(sc_X_test)

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [27]:
MAE= mean_absolute_error(y_test, r_test_pred)

In [28]:
MSE= mean_squared_error(y_test,r_test_pred)

In [29]:
MAE

0.5621969787129809

In [30]:
MSE

0.5832130131233201

In [31]:
RMSE= np.sqrt(MSE)

In [32]:
RMSE

np.float64(0.7636838436966701)

### Ridge Regression Cross Validation(CV)

In [33]:
from sklearn.linear_model import RidgeCV

In [37]:
r_cv_model= RidgeCV(alphas=(0.1,1.0,10)) # here we are taking a range of alpha

In [38]:
r_cv_model.fit(sc_X_train,y_train)

RidgeCV(alphas=(0.1, 1.0, 10))

In [40]:
r_cv_model.alpha_

np.float64(0.1)

In [41]:
r_cv_test_pred= r_cv_model.predict(sc_X_test)

In [45]:
r_cv_test_pred #r_cv means ridge cross validation

array([14.33666366, 19.17080825, 12.44768125, 17.07506541,  7.77669284,
        6.88054234, 20.00080764, 17.23724804, 10.31134388, 19.83414086,
        9.54010149, 13.91905884, 11.82108656, 23.16697739, 19.25561941,
        9.32074415, 12.38160887,  9.15283882,  8.54746856, 21.40950807,
        6.91480574, 19.33506029, 27.30740348, 24.42735771,  9.04450167,
       11.46282037, 20.64376899,  9.51081038, 12.50637366,  8.40374157,
        8.80855158, 19.89344344, 10.75887699,  7.10384794, 18.13625715,
        9.40543014, 10.49418333,  9.62050361,  7.28994516, 10.74117291,
       12.36190208, 10.389741  , 11.40585783,  7.71845447, 11.68205158,
       10.50439237,  5.60489419, 15.30072794, 13.06677993, 22.55994874])

In [46]:
MAE_cv= mean_absolute_error(y_test, r_cv_test_pred)

In [47]:
MSE_cv= mean_squared_error(y_test,r_cv_test_pred)

In [48]:
RMSE_cv= np.sqrt(MSE_cv)

In [49]:
MAE_cv

0.38466501703206646

In [50]:
MSE_cv

0.28955867336555163

In [51]:
RMSE_cv

np.float64(0.5381065632061661)

In [52]:
r_cv_model.coef_

array([ 6.00094099,  0.43262117,  0.63659122, -7.01858011,  4.53058545,
       -1.51960541, -0.56161524,  0.17815529,  0.0542098 ,  2.94219203,
       -1.20349296,  0.89495427,  0.39154019,  0.07430118,  0.13149428,
        0.3233214 , -0.2744754 , -0.01214972, -0.13641865])

### LASSO

In [53]:
from sklearn.linear_model import LassoCV

In [57]:
lasso_cv_m= LassoCV(eps=0.1,n_alphas=100,cv=5) #(epsilon, no of alphas, cross validation)

In [59]:
lasso_cv_m.fit(sc_X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [60]:
lasso_cv_m.alpha_

np.float64(0.4955891288263106)

In [61]:
lasso_cv_pred= lasso_cv_m.predict(sc_X_test)

In [62]:
lasso_cv_pred

array([13.3951229 , 19.24320744, 11.87748631, 15.61123352,  9.52213352,
        8.84164068, 20.13065479, 16.87162737, 10.26056178, 19.33626342,
       10.46991296, 13.49202742, 11.82055502, 21.95065147, 18.47813708,
       10.11706855, 12.50106882,  9.56628277,  9.52312879, 20.89165637,
        8.94003401, 18.14118047, 27.16468863, 24.23851376,  9.82488748,
       11.38882265, 21.15728578,  9.79506205, 12.16368692,  9.36509457,
        9.49801506, 19.37679451, 10.63725607,  8.65085402, 17.18971476,
        9.5980862 , 10.49080684,  9.92427938,  8.88740417, 10.6201079 ,
       11.92316245, 10.28113522, 11.05358087,  8.94638989, 11.52052874,
       10.71953312,  8.50045629, 15.13307845, 12.68907758, 21.32806824])

In [63]:
MAE_lasso_cv= mean_absolute_error(y_test,lasso_cv_pred)

In [64]:
MSE_lasso_cv= mean_squared_error(y_test,lasso_cv_pred)

In [65]:
RMSE_lasso_cv= np.sqrt(MSE_lasso_cv)

In [66]:
MAE_lasso_cv

0.6241496332838828

In [67]:
MSE_lasso_cv

0.9355589456162761

In [68]:
RMSE_lasso_cv

np.float64(0.9672429610063213)

In [69]:
lasso_cv_m.coef_

array([1.03575888, 0.        , 0.        , 0.        , 3.79481506,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

### Elastic Net

In [70]:
from sklearn.linear_model import ElasticNetCV

In [71]:
e_model= ElasticNetCV(l1_ratio=[0.01,0.1,0.5,0.9,1],
                     eps=0.1,
                     cv=5)

In [72]:
e_model.fit(sc_X_train,y_train)

ElasticNetCV(cv=5, eps=0.1, l1_ratio=[0.01, 0.1, 0.5, 0.9, 1])

In [73]:
e_model.l1_ratio_

np.float64(1.0)

In [74]:
e_model.alpha_

np.float64(0.4955891288263106)

In [75]:
e_model.coef_

array([1.03575888, 0.        , 0.        , 0.        , 3.79481506,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [76]:
e_model_pred= e_model.predict(sc_X_test)

In [77]:
MAE_en= mean_absolute_error(y_test,e_model_pred)

In [78]:
MAE_en

0.6241496332838828

In [79]:
MSE_en= mean_squared_error(y_test,e_model_pred)

In [81]:
MSE_en

0.9355589456162761

In [82]:
RMSE_en= np.sqrt(MSE_en)

In [83]:
RMSE_en

np.float64(0.9672429610063213)

### Grid Search

In [84]:
from sklearn.model_selection import GridSearchCV

In [86]:
from sklearn.linear_model import ElasticNet

In [87]:
param_grid={
    'alpha': [0.1,1.5,10,50,100],
    'l1_ratio': [0.1,0.5,0.7,0.9,0.95,0.99,1]
}

In [88]:
base_elastic_model= ElasticNet()

In [90]:
grid_model= GridSearchCV(estimator= base_elastic_model,
             param_grid= param_grid,
             cv=5)

In [91]:
grid_model.fit(sc_X_train,y_train)

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1.5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]})

In [92]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=0.99)

In [93]:
grid_model.predict(sc_X_test)

array([13.47416944, 19.64413178, 11.74760417, 15.92671241,  8.8441644 ,
        7.91815805, 20.53740136, 17.27251336, 10.06716283, 19.86841797,
       10.09738554, 13.66876371, 11.91462254, 22.69850489, 19.00703229,
        9.57498311, 12.54064885,  9.06546452,  8.80433975, 21.49004617,
        8.08344256, 18.66605907, 27.80406093, 24.85130829,  9.23287071,
       11.45098956, 21.39855981,  9.16566787, 12.21947692,  8.89649318,
        8.91721381, 19.91312378, 10.45434169,  7.66918081, 17.64065264,
        9.11018812, 10.08514145,  9.46606759,  8.22623212, 10.52340473,
       11.74687762, 10.08618815, 10.76338883,  8.1079285 , 11.26018052,
       10.30377693,  7.67064257, 15.40999442, 12.81466089, 22.04369113])

In [94]:
grid_pred= grid_model.predict(sc_X_test)

In [95]:
np.sqrt(mean_squared_error(y_test,grid_pred))

np.float64(0.7274671126171618)