### Importing NumPy library

In [1]:
import numpy as np

### NumPy Array
* Vector strictly 1-D Array
* Matrices: 2-D (matrix can strill have only 1 row or 1 column)

##### Why Numpy and not just a List:
1. Memory Efficient
2. Easily Expandable to N-dimensions
3. Better computational speed
4. Broadcasting Operations and Functions

# Creating a NumPy Arrays from Objects

#### From a Python List

In [2]:
mylist= [1,2,3,4,5,6]
type(mylist)

list

In [3]:
myarray= np.array(mylist)
myarray

array([1, 2, 3, 4, 5, 6])

In [4]:
type(myarray)

numpy.ndarray

In [5]:
mymatrix= [[1,2,3],[4,5,6],[7,8,9]]
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Built in methods to create Arrays:

In [7]:
#arange returns evenly spaced values within a given interval

np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
#arange returns evenly spaced values within a given interval

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,78)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77])

In [10]:
np.arange(10,78,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [12]:
# zeros and ones

np.zeros(7) # this will give a 1D array of 0s 7 times

array([0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(4,3)

TypeError: Cannot interpret '3' as a data type

In [14]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#linspace: returns evenly spaced numbers over a specified interval

np.linspace(0,10,4) # this will give 4 numbers btw 0 and 10

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [19]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [21]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [23]:
# eye

np.eye(4) #this will create an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

#### rand: creates an array of the given shape and populates it with random samples from a uniform distribution over (0,1)

In [24]:
np.random.rand(8)

array([0.43671885, 0.6203318 , 0.26736246, 0.11828323, 0.26306358,
       0.3021426 , 0.5885613 , 0.94409671])

In [26]:
np.random.rand(4)

array([0.67660128, 0.79636486, 0.79608105, 0.07102484])

In [27]:
np.random.rand(4)

array([0.09668526, 0.57788148, 0.01589349, 0.77871274])

In [31]:
#randint: returns random integers from low (inclusive) to high (exclusive)

np.random.randint(480,900)

846

In [32]:
np.random.randint(480,900,20)

array([831, 579, 663, 776, 790, 518, 798, 486, 863, 794, 897, 658, 807,
       570, 534, 732, 867, 771, 643, 656], dtype=int32)

In [33]:
np.random.randint(480,900,4)

array([799, 857, 741, 587], dtype=int32)

In [34]:
type(np.random.randint(480,900))

int

In [35]:
type(np.random.randint(480,900,4))

numpy.ndarray

In [36]:
np.random.randint(480,900,(4,3))

array([[766, 721, 736],
       [663, 852, 882],
       [505, 803, 745],
       [867, 610, 805]], dtype=int32)

In [37]:
type(np.random.randint(480,900,(4,3)))

numpy.ndarray

In [44]:
#seed: sets the random state so that same 'random' results can be reproduced

np.random.seed(90) # random state parameters in several ML algo
np.random.randint(40,900,(2,3))

array([[899, 709, 666],
       [711, 363, 719]], dtype=int32)

In [45]:
np.random.seed(45) # random state parameters in several ML algo
np.random.randint(40,900,(2,3))

array([[454, 683, 584],
       [647, 765, 203]], dtype=int32)

### Array Attributes and Methods

In [46]:
arr= np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ranarr= np.random.randint(0,50,12)
ranarr

array([13, 11, 42, 16, 24, 47, 48, 41, 31, 34, 22, 39], dtype=int32)

In [59]:
#reshape: returns an array containing the same data with a new shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
ranarr_2D= np.random.randint(0,50,(3,4))
ranarr_2D

array([[27, 32, 16, 11],
       [41, 32,  6, 32],
       [40, 16, 38, 28]], dtype=int32)

In [61]:
# shape: attribute that gives you the shape of the numpy array

ranarr.shape

(12,)

In [62]:
ranarr_2D.shape

(3, 4)

In [63]:
type(ranarr_2D.shape)

tuple

In [64]:
ranarr

array([13, 11, 42, 16, 24, 47, 48, 41, 31, 34, 22, 39], dtype=int32)

In [65]:
ranarr.reshape(6,2)

array([[13, 11],
       [42, 16],
       [24, 47],
       [48, 41],
       [31, 34],
       [22, 39]], dtype=int32)

In [66]:
ranarr.reshape(4,3)

array([[13, 11, 42],
       [16, 24, 47],
       [48, 41, 31],
       [34, 22, 39]], dtype=int32)

In [68]:
ranarr_1_12=ranarr.reshape(1,12)
ranarr_1_12

array([[13, 11, 42, 16, 24, 47, 48, 41, 31, 34, 22, 39]], dtype=int32)

In [69]:
ranarr_12_1=ranarr.reshape(12,1)
ranarr_12_1

array([[13],
       [11],
       [42],
       [16],
       [24],
       [47],
       [48],
       [41],
       [31],
       [34],
       [22],
       [39]], dtype=int32)

In [70]:
ranarr_1_12.shape

(1, 12)