In [2]:
import numpy as np

arr= np.arange(11,40,3)
arr

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [3]:
# get a value at an index

arr[3]

np.int64(20)

In [4]:
arr[-2]

np.int64(35)

In [5]:
# get values in a range

arr[1:4]

array([14, 17, 20])

In [6]:
arr[1:-6]

array([14, 17, 20])

In [7]:
arr[:3]

array([11, 14, 17])

In [8]:
arr[:]

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [9]:
arr

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

### Broadcasting

In [10]:
# setting a value with index range

arr[:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,  26,  29,  32,  35,  38])

In [12]:
# resetting the array

arr= np.arange(11,40,3)
arr

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [13]:
slice_of_array= arr[:5]

In [14]:
slice_of_array

array([11, 14, 17, 20, 23])

In [15]:
slice_of_array[:4]=99
slice_of_array

array([99, 99, 99, 99, 23])

In [16]:
arr

array([99, 99, 99, 99, 23, 26, 29, 32, 35, 38])

### Data is not copied. 'Slice of array' is just a view of original array. This avoid memory problem.

In [17]:
# resetting the array again

arr= np.arange(11,40,3)
arr

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [18]:
arr_copy= arr.copy() #to get a copy, need to be explicit

arr_copy

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [19]:
slice_of_array=arr_copy[:5]
slice_of_array

array([11, 14, 17, 20, 23])

In [20]:
slice_of_array[:4]=90

In [21]:
slice_of_array

array([90, 90, 90, 90, 23])

In [22]:
arr_copy

array([90, 90, 90, 90, 23, 26, 29, 32, 35, 38])

In [23]:
arr

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

### Indexing and Selection of 2D arrays(Matrices)

In [24]:
arr_2d= np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[1]

array([20, 25, 30])

In [26]:
arr_2d[1][2]

np.int64(30)

In [27]:
arr_2d[-2][-1]

np.int64(30)

In [33]:
arr_2d[1,2] #[row,columns]

np.int64(30)

In [34]:
arr_2d[-2,-1]

np.int64(30)

In [31]:
arr_2d[-2,2]

np.int64(30)

In [32]:
arr_2d[1,-1]

np.int64(30)

In [35]:
arr_2d[0,2]

np.int64(15)

In [36]:
arr_2d[-2,-3]

np.int64(20)

### 2D array slicing

In [37]:
ranarr_2d= np.random.randint(0, 50, (3, 4))
ranarr_2d

array([[40,  7,  1, 23],
       [14, 42,  7, 24],
       [13, 15, 16,  7]], dtype=int32)

In [38]:
ranarr_2d[0:2,0:2]

array([[40,  7],
       [14, 42]], dtype=int32)

In [39]:
ranarr_2d[:2,:2]

array([[40,  7],
       [14, 42]], dtype=int32)

In [40]:
ranarr_2d[1:2,1:3]

array([[42,  7]], dtype=int32)

In [41]:
ranarr_2d[-2:-1,-3:-1]

array([[42,  7]], dtype=int32)

In [42]:
ranarr_2d[:,2]

array([ 1,  7, 16], dtype=int32)

In [43]:
ranarr_2d[-2,:]

array([14, 42,  7, 24], dtype=int32)

### Conditional Selection

In [44]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
boolean_array= arr>4
boolean_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [47]:
arr(boolean_array==True)

TypeError: 'numpy.ndarray' object is not callable

In [48]:
arr[boolean_array==True]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[boolean_array==False]

array([0, 1, 2, 3, 4])

In [50]:
arr[boolean_array]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr=np.arange(11,40,3)
arr

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [53]:
arr[arr>20]

array([23, 26, 29, 32, 35, 38])

In [54]:
arr[arr<40/2]

array([11, 14, 17])