### Arithmetic

In [1]:
import numpy as np

In [2]:
arr= np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr/arr

C:\Users\Taneja\AppData\Local\Temp\ipykernel_15896\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
arr+8

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [8]:
1/arr

C:\Users\Taneja\AppData\Local\Temp\ipykernel_15896\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Universal Array Functions

https://numpy.org/doc/stable/reference/ufuncs.html

In [11]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [12]:
# sqrt

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
#exponential

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
#sin function

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [16]:
# natural log

np.log(arr)

C:\Users\Taneja\AppData\Local\Temp\ipykernel_15896\4224204831.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Summary Statistics on Array

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr.sum()

np.int64(45)

In [20]:
arr.mean()

np.float64(4.5)

In [21]:
arr.max()

np.int64(9)

In [22]:
arr.min()

np.int64(0)

In [23]:
arr.var()

np.float64(8.25)

In [24]:
arr.std()

np.float64(2.8722813232690143)

#### Axis Logic
* axis0: vertical axis (rows)
* axis1: horizontal axis (columns)

In [25]:
ranarr_2d = np.random.randint (0, 50, (3, 4)) 
ranarr_2d

array([[44, 38,  5, 22],
       [20, 12,  1, 32],
       [19,  9,  4, 23]], dtype=int32)

In [26]:
ranarr_2d.sum(axis=0)

array([83, 59, 10, 77])

In [27]:
ranarr_2d.sum(axis=1)

array([109,  65,  55])

In [28]:
ranarr_2d.mean(axis=0)

array([27.66666667, 19.66666667,  3.33333333, 25.66666667])

In [29]:
ranarr_2d.mean(axis=1)

array([27.25, 16.25, 13.75])

In [30]:
ranarr_2d.std(axis=0)

array([11.55662388, 13.02134999,  1.69967317,  4.49691252])

In [32]:
ranarr_2d.std(axis=1)

array([15.15544457, 11.32199187,  7.59522877])